export default Rental = [
    {
        "id": 0,
        "type": "Home",
        "address1": "34 White Lily Ct",
        "listing_id": 1,
        "amount": 1.3,
        "currency": "MATIC",
        "city": "Sacramento",
        "state": "CA",
        "zipcode": "95833",
        "price": "625000",
        "beds": "3",
        "baths": "4",
        "src": "https://bafkreidao7wigddtsp7gwxuvxcheelt5rh2uo5talgbbcvyqq6bgkk43by.ipfs.dweb.link/",
        "sqft": "3444",
        "description": "Welcome to the newest neighborhood within the Twelve Bridges master-planned community in Lincoln, CA. Envision exquisite architecture paired with flexible floorplans – designed for energetic families.",
        "coordinates": [38.610390, -121.538600]
    },
    {
        "id": 1,
        "amount": 1.3,
        "type": "Apartment",
        "currency": "MATIC",
        "address1": "2419 Linden St",
        "listing_id": 5,
        "city": "Oakland",
        "state": "CA",
        "zipcode": "94607",
        "price": "650000",
        "beds": "2",
        "baths": "3",
        "sqft": "2000",
        "src": "https://bafkreigfrphsofaldcuhajes7ujhc3t2clu5ucqu6eu5pco3eked4ymhsa.ipfs.dweb.link/",
        "description": "Discover a new home experience tucked away within the Solaire master-planned community in Roseville, CA. Offering single & two-story homes with unique spaces to work & play.",
        "coordinates": [37.817160, -122.281390]
    },
    {
        "id": 2,
        "amount": 1.3,
        "type": "Town House",
        "currency": "SOL",
        "address1": "9435 Tensil Town",
        "city": "San Jose",
        "state": "CA",
        "zipcode": "95624",
        "price": "773000",
        "beds": "2",
        "listing_id": 6,
        "baths": "4",
        "sqft": "2200",
        "src": "https://bafybeiekwpovqccbj7hgy3hbgcnrt7gjwhgrz42477ykqmkn5yrhjj62aq.ipfs.dweb.link/",
        "description": "Discover a new home experience tucked away within the In SF",
        "coordinates": [37.3382, 121.8863]
    },
    {
        "id": 3,
        "amount": 1.3,
        "type": "Home",
        "currency": "ETH",
        "address1": "Sutter Way",
        "city": "San  Francisco",
        "state": "CA",
        "zipcode": "94129",
        "price": "773000",
        "beds": "2",
        "listing_id": 7,
        "baths": "4",
        "sqft": "2200",
        "src": "https://bafkreifz4ovfmblqh7wbyapufkp4pva6vf6iuwdt7r5bf567pxg3hx6emq.ipfs.dweb.link/",
        "description": "Discover the beautiful sites",
        "coordinates": [37.7749, 122.4194]
    }
]